name: vesta
description: Live tv app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  card_swiper: ^2.0.4
  glassmorphism_ui: ^0.3.0
  quiver: ^3.1.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.8  
  cloud_firestore: ^3.1.13  
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  firebase_analytics: ^9.1.9
  firebase_performance: ^0.8.0+13
  firebase_app_check: ^0.0.6+13
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.3
  device_info_plus: ^3.2.4
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.3
  dropdown_search: ^5.0.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  better_player: ^0.0.83
  video_player: ^2.4.4
  search_page: ^2.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_to_model: ^3.0.1
  hive_generator:
  build_runner:

flutter:
  assets: 
    - assets/images/

  uses-material-design: true

flutter_native_splash:

  color: "#5C258D"

  image: assets/images/logo.png

  android_12:
  
    color: "#5C258D"
    icon_background_color: "#5C258D"

 